"""empty message

Revision ID: 8cd17e462d02
Revises: 3861ef8585ac
Create Date: 2023-05-21 04:51:07.637556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "8cd17e462d02"
down_revision = "3861ef8585ac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("restaurant_id", postgresql.UUID(as_uuid=True), nullable=True)
    )
    op.create_foreign_key(
        None, "user", "restaurant", ["restaurant_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_column("user", "restaurant_id")
    # ### end Alembic commands ###
