"""empty message

Revision ID: 9588e1ff9ccb
Revises: 2c204db83dcf
Create Date: 2023-05-29 10:18:57.088901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9588e1ff9ccb'
down_revision = '2c204db83dcf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_refresh_token_id_fkey', 'cart', type_='foreignkey')
    op.drop_column('cart', 'refresh_token_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('refresh_token_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('cart_refresh_token_id_fkey', 'cart', 'refresh_token', ['refresh_token_id'], ['id'])
    # ### end Alembic commands ###
