"""empty message

Revision ID: b96b61e31844
Revises: df22ab21c25b
Create Date: 2023-05-22 01:42:06.666233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96b61e31844'
down_revision = 'df22ab21c25b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('city_district', sa.TEXT(), nullable=False))
    op.create_unique_constraint(None, 'restaurant', ['address_id'])
    op.create_unique_constraint(None, 'restaurant', ['user_id'])
    op.create_unique_constraint(None, 'restaurant', ['name'])
    op.create_unique_constraint(None, 'restaurant', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurant', type_='unique')
    op.drop_constraint(None, 'restaurant', type_='unique')
    op.drop_constraint(None, 'restaurant', type_='unique')
    op.drop_constraint(None, 'restaurant', type_='unique')
    op.drop_column('address', 'city_district')
    # ### end Alembic commands ###
